#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_world_stream = env_modules.Clone()

env_world_stream.add_source_files(env.modules_sources, "*.cpp")
